// src/adapters/seatplan.js
// ---------------------------------------------------------
// AJSEE SeatPlan adapter
//
// Loads normalized static data generated by scripts/fetch-seatplan.mjs.
// Pilot scope: only return SeatPlan events for explicit UK/London/theatre intent.
// ---------------------------------------------------------

const DATA_URL = '/data/seatplan-events.json';

let cachePromise = null;

function normalizeText(value = '') {
  return String(value || '')
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/['’`´]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function normalizeCountryCode(value = '') {
  const raw = String(value || '').trim().toUpperCase();
  if (raw === 'UK') return 'GB';
  return /^[A-Z]{2}$/.test(raw) ? raw : '';
}

function readFilterCountry(filters = {}) {
  return normalizeCountryCode(
    filters.countryCode ||
    filters.country ||
    filters.cc ||
    filters.cityCc ||
    filters.cityCountryCode ||
    ''
  );
}

function hasLondonIntent(filters = {}) {
  const city = normalizeText(filters.city || filters.cityLabel || filters.location || '');
  const keyword = normalizeText(filters.keyword || filters.q || filters.search || '');
  const category = normalizeText(filters.category || filters.segment || '');

  if (city === 'london' || city === 'londyn') return true;

  if (
    keyword.includes('london') ||
    keyword.includes('londyn') ||
    keyword.includes('theatre') ||
    keyword.includes('theater') ||
    keyword.includes('musical') ||
    keyword.includes('west end')
  ) {
    return true;
  }

  if (
    category === 'theatre' ||
    category === 'divadlo' ||
    category === 'musical' ||
    category === 'musicals'
  ) {
    return true;
  }

  return false;
}

function shouldLoadSeatPlan(filters = {}) {
  const cc = readFilterCountry(filters);

  if (cc === 'GB') return true;
  if (hasLondonIntent(filters)) return true;

  return false;
}

async function loadSeatPlanPayload() {
  if (!cachePromise) {
    cachePromise = fetch(DATA_URL, { cache: 'no-store' })
      .then((response) => {
        if (!response.ok) {
          throw new Error(`SeatPlan data fetch failed: ${response.status}`);
        }

        return response.json();
      })
      .catch((error) => {
        cachePromise = null;
        throw error;
      });
  }

  return cachePromise;
}

function eventText(event = {}) {
  return normalizeText([
    event.title?.en,
    event.title?.cs,
    event.description?.en,
    event.description?.cs,
    event.location?.city,
    event.venue?.name,
    event.rawUrl,
    event.category,
    ...(Array.isArray(event.categories) ? event.categories : []),
    ...(Array.isArray(event.types) ? event.types : [])
  ].filter(Boolean).join(' '));
}

function matchesKeyword(event = {}, keyword = '') {
  const q = normalizeText(keyword);
  if (!q) return true;

  return eventText(event).includes(q);
}

function matchesCity(event = {}, city = '') {
  const q = normalizeText(city);
  if (!q) return true;

  const cityText = normalizeText(event.location?.city || event.venue?.city || '');

  if (q === 'london' || q === 'londyn') {
    return cityText === 'london';
  }

  return cityText.includes(q);
}

function matchesCountry(event = {}, filters = {}) {
  const want = readFilterCountry(filters);
  if (!want) return true;

  const actual = normalizeCountryCode(event.countryCode || event.country || event.location?.country || '');
  return actual === want;
}

function matchesCategory(event = {}, filters = {}) {
  const category = normalizeText(filters.category || filters.segment || 'all');
  if (!category || category === 'all') return true;

  const values = [
    event.category,
    ...(Array.isArray(event.categories) ? event.categories : []),
    ...(Array.isArray(event.types) ? event.types : [])
  ].map(normalizeText);

  if (category === 'theatre' || category === 'divadlo') {
    return values.includes('theatre') ||
      values.includes('london theatre') ||
      values.includes('plays') ||
      values.includes('musicals');
  }

  return values.includes(category);
}

function toMillis(value = '') {
  if (!value) return NaN;

  const match = String(value).match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (match) {
    return new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3]), 12, 0, 0, 0).getTime();
  }

  return new Date(value).getTime();
}

function matchesDate(event = {}, filters = {}) {
  const from = String(filters.dateFrom || filters.from || '').trim();
  const to = String(filters.dateTo || filters.to || '').trim();

  if (!from && !to) return true;

  const eventFrom = toMillis(event.dateFrom || event.date || event.datetime);
  const eventTo = toMillis(event.dateTo || event.bookingUntil || event.dateFrom || event.date || event.datetime);

  if (!Number.isFinite(eventFrom) && !Number.isFinite(eventTo)) return false;

  const fromMs = from ? toMillis(from) : NaN;
  const toMs = to ? toMillis(to) : NaN;

  if (Number.isFinite(toMs) && Number.isFinite(eventFrom) && eventFrom > toMs) return false;
  if (Number.isFinite(fromMs) && Number.isFinite(eventTo) && eventTo < fromMs) return false;

  return true;
}

function localizedValue(value, fallback = '') {
  if (typeof value === 'string') return value;
  if (value && typeof value === 'object') {
    return value.en || value.cs || Object.values(value).find(Boolean) || fallback;
  }

  return fallback;
}

function withRuntimeDefaults(event = {}) {
  const titleText = localizedValue(event.title, event.name || '');
  const descriptionText = localizedValue(event.description, '');

  const city =
    event.city ||
    event.location?.city ||
    event.venue?.city ||
    'London';

  const venueName =
    event.venueName ||
    event.venue?.name ||
    event.location?.venue ||
    '';

  const tickets = event.tickets || event.url || '';

  return {
    ...event,

    // Compatibility fields for shared AJSEE filtering/rendering.
    title: titleText || event.title || 'Untitled',
    titleI18n: event.title,
    name: event.name || titleText,
    descriptionText,

    city,
    venueName,

    place: {
      ...(event.place || {}),
      city,
      country: event.country || event.countryCode || 'GB',
      venue: venueName
    },

    location: {
      ...(event.location || {}),
      city,
      country: event.country || event.countryCode || 'GB',
      venue: event.location?.venue || venueName
    },

    venue: {
      ...(event.venue || {}),
      city,
      name: venueName || event.venue?.name || ''
    },

    partner: 'seatplan',
    source: 'seatplan',
    bookingProvider: 'seatplan',

    country: event.country || 'GB',
    countryCode: event.countryCode || 'GB',
    category: event.category || 'theatre',

    tickets,
    url: event.url || tickets
  };
}

export async function fetchEvents({ locale = 'en-GB', filters = {} } = {}) {
  if (!shouldLoadSeatPlan(filters)) {
    return [];
  }

  const payload = await loadSeatPlanPayload();
  const events = Array.isArray(payload?.events) ? payload.events : [];

  const city = filters.city || filters.cityLabel || '';
  const keyword = filters.keyword || filters.q || filters.search || '';

  return events
    .map(withRuntimeDefaults)
    .filter((event) => matchesCountry(event, filters))
    .filter((event) => matchesCity(event, city))
    .filter((event) => matchesKeyword(event, keyword))
    .filter((event) => matchesCategory(event, filters))
    .filter((event) => matchesDate(event, filters));
}

export default { fetchEvents };