backend:
  name: git-gateway
  branch: main

media_folder: "public/images/microguides"    # kam se ukládají uploady v repu
public_folder: "/images/microguides"         # jak budou dostupné na webu

locales: [cs, en, de, sk, pl, hu]            # pro pohodlí v UI
i18n:
  structure: multiple_files                   # každý jazyk samostatný soubor
  locales: [cs, en, de, sk, pl, hu]
  default_locale: cs

collections:
  - name: "microguides"
    label: "Micro-guides"
    label_singular: "Micro-guide"
    folder: "content/microguides"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}.{{locale}}"
    i18n: true
    fields:
      - { label: "Slug", name: "slug", widget: "string", i18n: duplicate, hint: "např. seating-map" }
      - { label: "Název / Title", name: "title", widget: "string", i18n: translate }
      - { label: "Perex (krátký popis)", name: "summary", widget: "text", i18n: translate }
      - { label: "Čas čtení (min)", name: "readingMinutes", widget: "number", value_type: "int", min: 1, max: 15, i18n: duplicate }
      - { label: "OG/Hero obrázek", name: "cover", widget: "image", allow_multiple: false, i18n: duplicate }
      - { label: "Alt k hero obrázku", name: "coverAlt", widget: "string", i18n: translate }
      - { label: "Kategorie", name: "category", widget: "select", options: ["theatre", "concerts", "sports", "travel"], i18n: translate, required: false }
      - label: "Kroky / Steps"
        name: "steps"
        widget: "list"
        i18n: true
        fields:
          - { label: "ID kroku (kotva)", name: "id", widget: "string" }
          - { label: "Nadpis kroku", name: "heading", widget: "string" }
          - { label: "Text kroku (Markdown)", name: "body", widget: "markdown" }
          - { label: "Ilustrace", name: "image", widget: "image", required: false, i18n: duplicate }
          - { label: "Alt obrázku", name: "alt", widget: "string", required: false, i18n: translate }
      - { label: "CTA – otázka pod článkem", name: "ctaQuestion", widget: "string", i18n: translate, required: false }
      - { label: "Stav", name: "status", widget: "select", options: ["draft","published"], default: "draft", i18n: duplicate }
